<?php
return array (
  'option_group.acp' => 'Панель управления администратора',
  'option_group.alerts' => 'Оповещения пользователей и уведомления',
  'option_group.appearance' => 'Внешний вид',
  'option_group.attachments' => 'Вложения',
  'option_group.basicBoard' => 'Основные настройки',
  'option_group.boardActive' => 'Включение и отключение форума',
  'option_group.censoringOptions' => 'Автоцензор',
  'option_group.debug' => 'Настройки режима отладки',
  'option_group.discourager' => 'Нежелательные пользователи и наказание',
  'option_group.discussionOptions' => 'Темы, обсуждения и переписки',
  'option_group.emailOptions' => 'Настройки электронной почты',
  'option_group.imageLinkProxy' => 'Проксирование ссылок и изображений',
  'option_group.logging' => 'Настройки журналов',
  'option_group.mediaEmbedding' => 'Вставка медиа',
  'option_group.messageOptions' => 'Сообщения',
  'option_group.newsfeed' => 'Новостные ленты',
  'option_group.nodeList' => 'Узлы и список форумов',
  'option_group.performance' => 'Система и производительность',
  'option_group.pwa' => 'Настройки PWA',
  'option_group.searchOptions' => 'Настройки поиска',
  'option_group.seo' => 'Поисковая оптимизация (SEO)',
  'option_group.serviceProviders' => 'Внешние поставщики служб',
  'option_group.sharing' => 'Размещение публикаций в социальных сетях',
  'option_group.sitemap' => 'Генерация XML-карты сайта',
  'option_group.spam' => 'Управление спамом',
  'option_group.stats' => 'Статистики и метрики',
  'option_group.tagging' => 'Теги',
  'option_group.users' => 'Настройки пользователей',
  'option_group.usersAndRegistration' => 'Регистрация пользователей',
);